window.alert("Dear God, I've come to repent my sins");
window.alert("Let your blood wash me clean for I'm");
window.alert("I'm, I'm, I'm a rotten girl");
window.alert("I swore I'd never sin again");
window.alert("But my patience's running thin");
window.alert("The temptation flowing through my veins");
window.alert("I'm bounded by these shackles of shame");
window.alert("I promised I'd indulge no more");
window.alert("But my heart I can't ignore");
window.alert("In my dreams they're turning up the heat");
window.alert("I'm a dirty, rotten girl");
window.alert("On lock, underneath the bleachers");
window.alert("Just watch, look beyond the smoke and mirrors");
window.alert("Heart struck? Shun the nonbeliever");
window.alert("Our operation would never be complete");
window.alert("Red hot, tension with each whisper");
window.alert("Snapshot, quiet moans and muffled whimpers");
window.alert("Come on, can't you feel the fever");
window.alert("Rising up?");
window.alert("Rising up to the sky?");
window.alert("As testaments echo, fear ignites beneath my skin");
window.alert("The lord sayeth, 'Halt thy child, don't give into sin'");
window.alert("It's driving me crazy");
window.alert("The urge to forsake thee");
window.alert("Yet, something shifts within this wicked bliss");
window.alert("I swore I'd never sin again");
window.alert("But my patience's running thin");
window.alert("Student council breathing down my neck");
window.alert("I wonder if they're hiding from me");
window.alert("Forbidden fruits before my eyes");
window.alert("And a taste that's so divine");
window.alert("My regrets rewriting history");
window.alert("I'm a sad, pathetic girl");
window.alert("Someone please tell me what to do");
window.alert("Because honestly, I just can't stop");
window.alert("I've been trying so hard and I can't stop");
window.alert("What would God think?");
window.alert("And, I-I know I'm supposed to be a good girl, but");
window.alert("Somehow, I just can't control myself");
window.alert("Every time I see them");
window.alert("Touching skin to skin");
window.alert("My mind goes");
window.alert("My mind goes");
window.alert("Kya-AAAAAAAAAHHHHH");
window.alert("Could Eve be our idol?");
window.alert("Could she lead us through the light?");
window.alert("We'd all be disciples of her lemon driven bite");
window.alert("Can somebody save me?");
window.alert("The urge to forsake thee");
window.alert("Still, something shifts within this wicked bliss...");
window.alert("The power resting in my hands");
window.alert("For my God has other plans");
window.alert("In salvation I can live my life");
window.alert("As an ordinary girl");
window.alert("I can't resist it anymore");
window.alert("Cause I smell slow burn galore");
window.alert("All the trauma from a cobblestone");
window.alert("Could never beat the devil in me");
window.alert("An honest sinner 'til I die");
window.alert("What's the harm if I don't mind?");
window.alert("With the paddle that empowers me");
window.alert("I can live a sinful life");